function kartmobil:makebike {name:{"color":"light_purple","italic":false,"text":"스톰 블레이드"},speed:415, accel:600, boost:226, corner:200, drift:470, gauge:43, boosttime:48, hideplayer:0, maxboostcount:3, defense:35, size:1, model:"nekter-stormblade"}
function kartmobil:makebike {name:{"color":"light_purple","italic":false,"text":"윈드 엣지"},speed:415, accel:596, boost:220, corner:215, drift:470, gauge:50, boosttime:50, hideplayer:0, maxboostcount:3, defense:32, size:1, model:"lpeng-wind"}
function kartmobil:makebike {name:{"color":"light_purple","italic":false,"text":"렉키"},speed:415, accel:589, boost:234, corner:220, drift:460, gauge:47, boosttime:53, hideplayer:0, maxboostcount:3, defense:34, size:1, model:"lpeng-reckie"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"은월검"},speed:423, accel:587, boost:202, corner:222, drift:450, gauge:18, boosttime:59, hideplayer:0, maxboostcount:2, defense:30, size:0, model:"gangryu-silvermoonsword"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"황금 축구공"},speed:423, accel:575, boost:207, corner:219, drift:460, gauge:20, boosttime:58, hideplayer:1, maxboostcount:2, defense:23, size:2, model:"tco-golden-soccerball"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"암흑 골머리"},speed:427, accel:570, boost:190, corner:210, drift:460, gauge:21, boosttime:60, hideplayer:0, maxboostcount:2, defense:49, size:1, model:"lpeng-skull"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"Pink Venom 몬스터"},speed:423, accel:590, boost:202, corner:218, drift:442, gauge:18, boosttime:61, hideplayer:0, maxboostcount:2, defense:54, size:2, model:"loggamja-pink"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"업사이드 다운"},speed:423, accel:590, boost:200, corner:214, drift:454, gauge:18, boosttime:60, hideplayer:0, maxboostcount:2, defense:35, size:2, model:"loggamja-upside"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"소녀 미소"},speed:423, accel:600, boost:190, corner:220, drift:444, gauge:19, boosttime:60, hideplayer:1, maxboostcount:2, defense:30, size:0, model:"innosday-miso"}

function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"네온 머슬카"},speed:438, accel:543, boost:196, corner:203, drift:470, gauge:17, boosttime:61, hideplayer:0, maxboostcount:2, defense:48, size:2, model:"lpeng-neon-muscle"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"옵티머스 투프라임"},speed:428, accel:568, boost:207, corner:212, drift:455, gauge:20, boosttime:56, hideplayer:1, maxboostcount:2, defense:49, size:1, model:"lpeng-transformer"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"핑크 래빗"},speed:408, accel:620, boost:228, corner:205, drift:452, gauge:16, boosttime:58, hideplayer:0, maxboostcount:2, defense:43, size:2, model:"lpeng-rabbit"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"골드 하운드"},speed:424, accel:595, boost:210, corner:187, drift:470, gauge:23, boosttime:57, hideplayer:0, maxboostcount:2, defense:43, size:2, model:"nekter-hound"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"디멘터"},speed:419, accel:598, boost:200, corner:210, drift:480, gauge:15, boosttime:62, hideplayer:0, maxboostcount:2, defense:40, size:2, model:"lpeng-dementer"}
function kartmobil:makebike {name:{"color":"light_purple","italic":false,"text":"소닉 더 헤지혹"},speed:430, accel:512, boost:279, corner:175, drift:494, gauge:30, boosttime:48, hideplayer:1, maxboostcount:3, defense:26, size:1, model:"asdf-sonic"}
function kartmobil:makebike {name:{"color":"light_purple","italic":false,"text":"섀도우 더 헤지혹"},speed:420, accel:555, boost:242, corner:240, drift:600, gauge:34, boosttime:40, hideplayer:1, maxboostcount:1, defense:62, size:1, model:"asdf-shadow"}

function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"관 갔다오"},speed:431, accel:565, boost:195, corner:212, drift:462, gauge:21, boosttime:59, hideplayer:1, maxboostcount:2, defense:42, size:2, model:"lpeng-daoth"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"스탠더드wii"},speed:423, accel:583, boost:205, corner:209, drift:470, gauge:16, boosttime:58, hideplayer:0, maxboostcount:2, defense:40, size:2, model:"kite-mariokart-wii"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"스탠더드8"},speed:427, accel:575, boost:189, corner:210, drift:468, gauge:18, boosttime:59, hideplayer:0, maxboostcount:2, defense:42, size:1, model:"kite-mariokart-8"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"팬텀"},speed:423, accel:600, boost:197, corner:190, drift:440, gauge:15, boosttime:56, hideplayer:0, maxboostcount:2, defense:42, size:2, model:"nekter-phantom"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"레이싱 카트"},speed:423, accel:588, boost:196, corner:210, drift:468, gauge:18, boosttime:58, hideplayer:0, maxboostcount:2, defense:38, size:1, model:"uprise-racekart"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"1톤 트럭"},speed:428, accel:589, boost:199, corner:208, drift:445, gauge:21, boosttime:53, hideplayer:0, maxboostcount:2, defense:52, size:2, model:"kite-bongo"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"실버 애로우"},speed:428, accel:579, boost:198, corner:198, drift:444, gauge:22, boosttime:60, hideplayer:0, maxboostcount:2, defense:42, size:2, model:"kite-silvertown"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"할로윈 머슬"},speed:423, accel:599, boost:190, corner:199, drift:460, gauge:17, boosttime:58, hideplayer:0, maxboostcount:2, defense:43, size:2, model:"nekter-halloween"}
function kartmobil:makekart {name:{"color":"light_purple","italic":false,"text":"메트로"},speed:439, accel:520, boost:220, corner:203, drift:465, gauge:22, boosttime:60, hideplayer:1, maxboostcount:2, defense:55, size:2, model:"loggamja-metro"}
function kartmobil:makebike {name:{"color":"light_purple","italic":false,"text":"캠핑 스쿠터"},speed:420, accel:566, boost:237, corner:210, drift:490, gauge:43, boosttime:50, hideplayer:0, maxboostcount:3, defense:30, size:1, model:"lpeng-doom-scooter"}
