function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"사이버 연카"},speed:428, accel:601, boost:189, corner:210, drift:480, gauge:14, boosttime:59, hideplayer:0, maxboostcount:2, defense:33, size:1, model:"kite-practice-cyber"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"연습카트 엑스트림"},speed:432, accel:576, boost:211, corner:194, drift:468, gauge:11, boosttime:60, hideplayer:0, maxboostcount:2, defense:32, size:1, model:"tco-practice-xtreme"}

function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"갤럭시 코튼"},speed:428, accel:582, boost:210, corner:218, drift:460, gauge:13, boosttime:60, hideplayer:0, maxboostcount:2, defense:30, size:2, model:"kite-cotton-xun"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"핑크 코튼"},speed:428, accel:589, boost:203, corner:212, drift:465, gauge:12, boosttime:62, hideplayer:0, maxboostcount:2, defense:33, size:2, model:"kite-pinkcotton"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"골든 코튼"},speed:428, accel:605, boost:190, corner:210, drift:468, gauge:12, boosttime:60, hideplayer:0, maxboostcount:2, defense:30, size:2, model:"lpeng-gold-cotton"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"다크 버스트"},speed:411, accel:669, boost:220, corner:176, drift:420, gauge:11, boosttime:58, hideplayer:0, maxboostcount:2, defense:35, size:2, model:"kite-darkburst"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"하드 솔리드"},speed:438, accel:554, boost:200, corner:215, drift:470, gauge:13, boosttime:60, hideplayer:0, maxboostcount:2, defense:50, size:2, model:"kite-phc-solid"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"마라톤 스프린트"},speed:431, accel:584, boost:190, corner:211, drift:468, gauge:9, boosttime:66, hideplayer:0, maxboostcount:2, defense:39, size:2, model:"kite-marathon-sprint"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"세이버 타이런트"},speed:425, accel:594, boost:200, corner:230, drift:485, gauge:12, boosttime:59, hideplayer:0, maxboostcount:2, defense:32, size:1, model:"lpeng-saberht"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"세인트 세이버"},speed:427, accel:607, boost:180, corner:210, drift:498, gauge:15, boosttime:58, hideplayer:0, maxboostcount:2, defense:35, size:1, model:"lpeng-saberz7"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"파라곤"},speed:428, accel:590, boost:200, corner:220, drift:480, gauge:12, boosttime:60, hideplayer:0, maxboostcount:2, defense:35, size:2, model:"siaskr-paragon"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"헤비 파라곤"},speed:428, accel:600, boost:200, corner:200, drift:480, gauge:10, boosttime:60, hideplayer:0, maxboostcount:2, defense:36, size:2, model:"lpeng-paragon"}

function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"그믐 산군"},speed:428, accel:588, boost:186, corner:260, drift:468, gauge:10, boosttime:59, hideplayer:0, maxboostcount:2, defense:33, size:1, model:"lpeng-blacktiger"}
function kartmobil:makebike {name:{"color":"yellow","italic":false,"text":"골든 스톰 블레이드"},speed:416, accel:600, boost:238, corner:201, drift:470, gauge:41, boosttime:50, hideplayer:0, maxboostcount:3, defense:30, size:1, model:"nekter-goldenstormblade"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"능력자 다오"},speed:428, accel:585, boost:200, corner:214, drift:480, gauge:13, boosttime:60, hideplayer:1, maxboostcount:2, defense:36, size:0, model:"tco-fearlessdao"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"멍지니"},speed:428, accel:600, boost:182, corner:230, drift:474, gauge:11, boosttime:59, hideplayer:1, maxboostcount:2, defense:35, size:0, model:"tco-absent-mined-diz"}
function kartmobil:makebike {name:{"color":"yellow","italic":false,"text":"흰 소"},speed:400, accel:660, boost:244, corner:199, drift:455, gauge:13, boosttime:58, hideplayer:1, maxboostcount:2, defense:74, size:1, model:"nekter-cow"}

function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"흑룡"},speed:423, accel:588, boost:200, corner:240, drift:490, gauge:15, boosttime:58, hideplayer:0, maxboostcount:2, defense:30, size:1, model:"nekter-blackdragon"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"스토커"},speed:428, accel:580, boost:205, corner:218, drift:488, gauge:14, boosttime:58, hideplayer:0, maxboostcount:2, defense:38, size:2, model:"nekter-stocker"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"스펙터"},speed:428, accel:601, boost:198, corner:212, drift:478, gauge:10, boosttime:60, hideplayer:0, maxboostcount:2, defense:31, size:2, model:"lpeng-specter"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"스팅레이"},speed:427, accel:590, boost:200, corner:196, drift:480, gauge:24, boosttime:59, hideplayer:0, maxboostcount:2, defense:34, size:1, model:"lpeng-stingray"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"어벤저"},speed:428, accel:590, boost:202, corner:220, drift:460, gauge:11, boosttime:60, hideplayer:0, maxboostcount:2, defense:37, size:2, model:"nekter-avenger"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"멘티스"},speed:424, accel:600, boost:205, corner:200, drift:479, gauge:28, boosttime:55, hideplayer:0, maxboostcount:3, defense:35, size:1, model:"ecyceeeee-mentis"}
function kartmobil:makekart {name:{"color":"yellow","italic":false,"text":"쉐퍼"},speed:426, accel:591, boost:200, corner:210, drift:472, gauge:22, boosttime:60, hideplayer:0, maxboostcount:3, defense:38, size:1, model:"lpeng-sheffer"}
